const greeting = (guest) => `Hello, ${guest}!`;

describe('greeting()', function(){ //test suite
   it('says hello', function(){ // test case
       expect(greeting('Jest')).toBe('Hello, Jest!');
   });
});

//expect() creates an assertion. It takes a single argument, typically a value generated by the code being tested, and returns an object that exposes a set of matcher functions.
//toBe()is a matcher that performs a strict equality test between the value being tested (the expect() argument) and the expected value (its own argument).